Document: deepin-software-center
Title: Debian deepin-software-center Manual
Author: <insert document author here>
Abstract: This manual describes what deepin-software-center is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/deepin-software-center/deepin-software-center.sgml.gz

Format: postscript
Files: /usr/share/doc/deepin-software-center/deepin-software-center.ps.gz

Format: text
Files: /usr/share/doc/deepin-software-center/deepin-software-center.text.gz

Format: HTML
Index: /usr/share/doc/deepin-software-center/html/index.html
Files: /usr/share/doc/deepin-software-center/html/*.html
